### ISSUE TITLE
Add predictions method/function in Yarrow Format

### ISSUE THREAD

**Issue by arthemide** [michelin/YarrowFormat#31]
## :dart: The goal/description

- [ ] Add method/function `get_predictions` that retrieve all annotations with contributor being `human: false`
- [ ] Add method/function `get_annotations` that retrieve all annotations with contributor being `human: true`

**Tasks for packages**
- [ ] Add on `Annotation` class the `confidence` variable
- [ ] `confidence` mandatory if contributor being `human: false` else Optional
- [ ] Validate `0 <= confidence <= 1`

## :trophy: Acceptance criteria

- [ ] Publish in Pypi both packages on release
